[world]
name = "Stark_Explorer"
description = "An Endless Explorer Game"
seed = "stark_explorer_1"

[namespace]
default = "Stark_Explorer_Game"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x021b99ae1a15b1f6c4f5e72d2cf7295ab1effa44172321600c6ac4554ce02c88"
world_block = "2528273"

[writers]
"Stark_Explorer_Game" = ["Stark_Explorer_Game-actions"]