[world]
name = "Stark_Explorer"
description = "A Space Explorer Game"
seed = "stark_explorer"

[namespace]
default = "Stark_Explorer_Game"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x057bec37a60c0a0f246d0c4f30b7f8202a46d921b056b5a712774177990e18c1"


[writers]
"Stark_Explorer_Game" = ["Stark_Explorer_Game-actions"]


